spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 00
    password: 00
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
  data:
    mongodb:
      uri: mongodb+srv://ssddo:0524@blogtracker.ytlnj.mongodb.net/blog?retryWrites=true&w=majority

logging:
  level:
    root: info
    org.springframework.data.mongodb: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight([%5p]) [%thread] %cyan(%logger) - %msg%n"